config/routes.rb
Rails.application.routes.draw do

  root to: 'index#index'
  get 'index' => 'index#index'
  post 'submit_contact_form' => 'index#submit_contact'
  get 'directorio' => 'index#medical_directory'
  get 'nuevo_chat' => 'index#new_chat' #usuario
  get 'enviar_mensaje' => 'index#send_message', as: 'send_message' #usuario
  get 'caracteristicas' => 'index#load_features', as: 'load_feature'
  get 'search_results' => 'index#search_results'
  get 'get_doctor_info' => 'index#get_doctor_info'
  get 'medsi_pdf_info' => 'index#medsi_pdf'
  get 'aviso_de_privacidad' => 'index#aviso_de_privacidad'
  post 'register_user' => 'index#register_user'
  post 'register_patient' => 'index#register_user_patient'
  get 'check_user' => 'index#check_user'
  get 'reset_doctor_password' => 'sessions#reset_doctor_password', as: 'reset_doctor_password'
  get 'send_password_mail' => 'sessions#send_password_mail'
  get 'reset_password' => 'sessions#reset_password'
  get 'picture_doctor' => 'index#picture_doctor'
  get 'picture_patient' => 'index#picture_patient'

  get 'login' => 'sessions#new',as: 'login_user'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'e401' => 'application#unauthorized_view_render'

  resources :news, :path => 'noticias', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' }

  namespace :cli do
    get 'index' => 'index#index'
    resources :tickets, :path => 'tickets', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'pago_admision/:id', to: 'tickets#admission_transaction', as: 'admission_transaction'
        get 'otros_pagos/:id', to: 'tickets#other_payments', as: 'other_payments'
      end
    end
    resources :emisor_fiscal_informations, :path => 'emisor_informacion_fiscal', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' }
    resources :suppliers, :path => 'proveedores', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' }
    resources :service_packages, :path => 'paquetes_servicios', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'manage_services/:id', to: 'service_packages#manage_services', as: 'manage_services'
        get 'add_service', to: 'service_packages#add_service', as: 'add_service'
        get 'delete_service', to: 'service_packages#delete_service', as: 'delete_service'

      end
    end
    resources :waste_types, :path => 'tipos_salida', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' }
    resources :insurances, :path => 'aseguradoras', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'prices', to: 'insurances#prices', as: 'prices'
        get 'get_services', to: 'insurances#get_services', as: 'get_services'
        get 'set_prices', to: 'insurances#set_prices', as: 'set_prices'
        get 'save_price', to: 'insurances#save_price', as: 'save_price'
        get 'active_insurence', to: 'insurances#active_insurence', as: 'active_insurence'
      end
    end
    resources :other_charges, :path => 'Generar_cobros', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'search_charges', to: 'other_charges#search_charges', as: 'search_charges'
        get 'charges_report', to: 'other_charges#charges_report', as: 'charges_report'
        get 'save_other_charge', to: 'other_charges#save_other_charge', as: 'save_other_charge'
        get 'get_charge_items', to: 'other_charges#get_charge_items', as: 'get_charge_items'
        get 'pay_other_charge', to: 'other_charges#pay_other_charge', as: 'pay_other_charge'
        get 'cancel_payment', to: 'other_charges#cancel_payment', as: 'cancel_payment'
        get 'close_other_charge', to: 'other_charges#close_other_charge', as: 'close_other_charge'
        get 'check_cancel_permission', to: 'other_charges#check_cancel_permission', as: 'check_cancel_permission'
        get 'check_close_permission', to: 'other_charges#check_close_permission', as: 'check_close_permission'
        get 'export_charges', to: 'other_charges#export_charges', as: 'export_charges'
        get 'print_charge_report', to: 'other_charges#print_charge_report', as: 'print_charge_report'
      end
    end
    resources :pharmacy_items, :path => 'articulos_farmacia', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'search_pharmacy_item', to: 'pharmacy_items#find_pharmacy_item', as: 'search_pharmacy_item'
      end
    end

    resources :medicament_purchases, :path => 'compra_medicamentos', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'save_purchase', to: 'medicament_purchases#save_purchase', as: 'save_purchase'
        get 'get_lot', to: 'medicament_purchases#get_lot', as: 'get_lot'
        get 'get_lot_medicament', to: 'medicament_purchases#get_lot_medicament', as: 'get_lot_medicament'
        get 'get_last_folio', to: 'medicament_purchases#get_last_folio', as: 'get_last_folio'

      end
    end
    resources :medicament_movements, :path => 'movimientos_medicamentos', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'pharmacy_movements', to: 'medicament_movements#pharmacy_movements', as: 'pharmacy_movements'
        post 'pharmacy_movement_save', to: 'medicament_movements#pharmacy_movement_save', as: 'pharmacy_movement_save'
      end
    end
    resources :medicament_wastes, :path => 'mermas_medicamentos', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'check_quantity', to: 'medicament_wastes#check_quantity', as: 'check_quantity'
        get 'check_quantity_pharmacy', to: 'medicament_wastes#check_quantity_pharmacy', as: 'check_quantity_pharmacy'
        get 'pharmacy_wastes', to: 'medicament_wastes#pharmacy_wastes', as: 'pharmacy_wastes'
        post 'pharmacy_waste_save', to: 'medicament_wastes#pharmacy_waste_save', as: 'pharmacy_waste_save'
      end
    end
    resources :hospitalizations, :path => 'hospitalizaciones', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        post 'save_medical_valoration', to: 'hospitalizations#save_medical_valoration', as: 'save_medical_valoration'
        post 'save_medical_annotation', to: 'hospitalizations#save_medical_annotation', as: 'save_medical_annotation'
        get 'load_annotation_fields', to: 'hospitalizations#load_annotation_fields', as: 'load_annotation_fields'
        get 'imprimir/:id', to: 'hospitalizations#print', as: 'print'
      end
    end
    resources :medical_annotation_images, :path => 'imagenes_nota_medica', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'descarga/:id', to: 'medical_annotation_images#download', as: 'download'
      end
    end
    resources :medical_annotation_files, :path => 'archivos_nota_medica', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'descarga/:id', to: 'medical_annotation_files#download', as: 'download'
      end
    end
    resources :medical_annotations, :path => 'notas_medicas', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'imprimir/:id', to: 'medical_annotations#print', as: 'print'
      end
    end
     resources :tooths, :path => 'odontología', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
       collection do
         get 'save_odontogram', to: 'tooths#save_odontogram', as: 'save_odontogram'
         get 'get_original_odontogram', to: 'tooths#get_original_odontogram', as: 'get_original_odontogram'
         get 'get_teeth_historial', to: 'tooths#get_teeth_historial', as: 'get_teeth_historial'
         get 'get_last_data', to: 'tooths#get_last_data', as: 'get_last_data'

       end
     end
    resources :admission_invoices, :path => 'facturas_admisiones', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'get_receptor_email', to: 'admission_invoices#get_receptor_email', as: 'get_receptor_email'
        get 'print_admission_invoice_pdf/:id', to: 'admission_invoices#print_admission_invoice_pdf', as: 'print_admission_invoice_pdf'
        get 'download_admission_invoice_xml/:id', to: 'admission_invoices#download_admission_invoice_xml', as: 'download_admission_invoice_xml'
        get 'cancel_admission_invoice', to: 'admission_invoices#cancel_admission_invoice', as: 'cancel_admission_invoice'
        get 'send_invoice_email', to: 'admission_invoices#send_invoice_email', as: 'send_invoice_email'

      end
    end
     resources :hospital_admissions, :path => 'admisiones_hospitalarias', :path_names => { :edit => 'editar', :delete => 'eliminar', :show => 'ver', :new => 'nuevo' } do
      collection do
        get 'print_pdf_admission/:id', to: 'hospital_admissions#print_pdf_admission', as: 'print_pdf_admission'
        get 'get_services_select', to: 'hospital_admissions#get_services_select', as: 'get_services_select'
        get 'stamp_admission_invoice', to: 'hospital_admissions#stamp_admission_invoice', as: 'stamp_admission_invoice'
        get 'get_payments', to: 'hospital_admissions#get_payments', as: 'get_payments'
        get 'get_emisor_info', to: 'hospital_admissions#get_emisor_info', as: 'get_emisor_info'

app/controllers/cli/admission_invoices_controller.rb
class Cli::AdmissionInvoicesController < ApplicationController
  load_and_authorize_resource :only => [:index]
  include Doctor::DailyCashesHelper
  include Doctor::FINKOK

  def index
    respond_to do |format|
      format.html
      format.json { render json: AdmissionInvoicesDatatable.new(view_context)}
    end
  end
  def get_receptor_email
    emails = []
    t = AdmissionInvoice.find(params[:invoice_id])
    if t != nil
        if t.hospital_admission.patient.email.present?
          emails.push({
                          number:0,
                          email:t.hospital_admission.patient.email
                      })
        end
        if t.hospital_admission.patient.patient_fiscal_informations.count > 0
          t.hospital_admission.patient.patient_fiscal_informations.each do |fiscal|
            if fiscal.email.present?
              emails.push({
                              number:1,
                              email:fiscal.email
                          })

            end
            if fiscal.email2.present?
              emails.push({
                              number:2,
                              email:fiscal.email2
                          })

            end
          end

        end

    end

    respond_to do |format|
      format.html { render json: {:emails => emails} }
    end
  end
  def print_admission_invoice_pdf
    inv = AdmissionInvoice.find(params[:id])
    respond_to do |format|
      format.pdf do
        render pdf: "Factura "+inv.serie+"-"+inv.folio.to_s,  locals: { :@invoice_data => inv }, template: 'cli/hospital_admissions/template_invoice.html.erb', layout: false,
               margin: { top: 5, bottom: 20, left: 5, right: 5 }, encoding: 'UTF-8', footer:  {   html: {   template:'cli/hospital_admissions/template_invoice_footer.html.erb', locals: {}}, center: 'TEXT',
                                                                                                  spacing:           1,
                                                                                                  line:              true
            }
      end
    end
  end
  def send_invoice_email
      inv = AdmissionInvoice.find(params[:invoice_id])

        pdf_name = "Factura "+inv.serie+"-"+inv.folio.to_s
        pdfs = render_to_string  pdf: "Factura "+inv.serie+"-"+inv.folio.to_s,  locals: { :@invoice_data => inv }, template: 'cli/hospital_admissions/template_invoice.html.erb', layout: false,
                                 margin: { top: 5, bottom: 20, left: 5, right: 5 }, encoding: 'UTF-8', footer:  {   html: {   template:'cli/hospital_admissions/template_invoice_footer.html.erb', locals: {}}, center: 'TEXT',
                                                                                                                    spacing:           1,
                                                                                                                    line:              true
            }

      emaillist = params[:email]
      if params[:emailp] != ""
        emaillist += ";" + params[:emailp]
      end
      if params[:emailf1] != ""
        emaillist += ";" + params[:emailf1]
      end
      if params[:emailf2] != ""
        emaillist += ";" + params[:emailf2]
      end
      if params[:extramails] != ""
        emaillist += ";" +params[:extramails]
      end
      SendInvoice.send_invoice(emaillist,pdfs,pdf_name,inv).deliver_now

      render :json => true, layout: false


    end
  def cancel_admission_invoice
    invoice = AdmissionInvoice.find(params[:invoice_id])
    doc = invoice.emisor_fiscal_information
    proveedor = Comprobante.new()
    pem = Dir.pwd + "/uploads/clinic_info/" + doc.id.to_s + "/certificate_key/key.pem"
    certificado =  %x'openssl x509 -inform DER -in #{doc.certificate_stamp.current_path.to_s}'
    resultado =  proveedor.cancela invoice.UUID, doc.rfc,pem, certificado.to_s
    if resultado != nil
      if resultado[:message] == "1"
        invoice.update(xml: resultado[:data],cancel:1)

        result_message = "Factura cancelada con exito"
        result_code = "1"
      else
        result_message = get_cancel_invoice_error resultado[:message]
        result_code = "0"
      end
    else
      result_message = "Ocurrio un error al intentar cancelar la factura."
      result_code = "0"
    end
    respond_to do |format|
      format.html { render json: {:message => result_message, :result => result_code} }
    end
  end


  def numero_a_palabras(numero)
    de_tres_en_tres = numero.to_i.to_s.reverse.scan(/\d{1,3}/).map{|n| n.reverse.to_i}

    millones = [
        {true => nil, false => nil},
        {true => 'millón', false => 'millones'},
        {true => "billón", false => "billones"},
        {true => "trillón", false => "trillones"}
    ]

    centena_anterior = 0
    contador = -1
    palabras = de_tres_en_tres.map do |numeros|
      contador += 1
      if contador%2 == 0
        centena_anterior = numeros
        [centena_a_palabras(numeros), millones[contador/2][numeros==1]].compact if numeros > 0
      elsif centena_anterior == 0
        [centena_a_palabras(numeros), "mil", millones[contador/2][false]].compact if numeros > 0
      else
        [centena_a_palabras(numeros), "mil"] if numeros > 0
      end
    end

    palabras.compact.reverse.join(' ')
  end
  def centena_a_palabras(numero)
    especiales = {
        11 => 'once', 12 => 'doce', 13 => 'trece', 14 => 'catorce', 15 => 'quince',
        10 => 'diez', 20 => 'veinte', 100 => 'cien'
    }
    if especiales.has_key?(numero)
      return especiales[numero]
    end

    centenas = [nil, 'ciento', 'doscientos', 'trescientos', 'cuatrocientos', 'quinientos', 'seiscientos', 'setecientos', 'ochocientos', 'novecientos']
    decenas = [nil, 'dieci', 'veinti', 'treinta', 'cuarenta', 'cincuenta', 'sesenta', 'setenta', 'ochenta', 'noventa']
    unidades = [nil, 'un', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve']

    centena, decena, unidad = numero.to_s.rjust(3,'0').scan(/\d/).map{|i| i.to_i}

    palabras = []
    palabras << centenas[centena]

    if especiales.has_key?(decena*10 + unidad)
      palabras << especiales[decena*10 + unidad]
    else
      tmp = "#{decenas[decena]}#{' y ' if decena > 2 && unidad > 0}#{unidades[unidad]}"
      palabras << (tmp.blank? ? nil : tmp)
    end

    palabras.compact.join(' ')
  end
  helper_method :numero_a_palabras
  def download_admission_invoice_xml
    inv = AdmissionInvoice.find(params[:id])
    xml_data = inv.xml
    respond_to do |format|
      format.xml { send_data render_to_string(xml: xml_data) ,:filename => 'Factura '+inv.serie+'-'+inv.folio.to_s+'.xml', :type=>"application/xml", :disposition => 'attachment' }
    end
  end


  private



end

app/controllers/cli/index_controller.rb
class Cli::IndexController < ApplicationController


  def index

  end
end

app/controllers/cli/medical_annotation_files_controller.rb
class Cli::MedicalAnnotationFilesController < ApplicationController

  def create
    annotation_file = MedicalAnnotationFile.new(medical_annotation_file_params)
    annotation_file.user = current_user
    if annotation_file.save
      case params[:source]
        when "hospitalization"
          redirect_to cli_hospitalization_path(params[:hospitalization_id])
      end
    end
  end

  def download
    annotation_file = MedicalAnnotationFile.find(params[:id])
    if is_image(annotation_file.document.url)
      send_file annotation_file.document.path, :disposition => 'inline'
    else
      send_file annotation_file.document.path
    end
  end

  def is_image(file)
    ext = File.extname(file)
    ['.png','.jpg','.jpeg','.bmp'].include? ext
  end

  private
  def medical_annotation_file_params
    params.require(:medical_annotation_file).permit(:medical_annotation_id,:notes, :document)
  end
end

app/views/cli/hospitalizations/_menu.html.erb
<div class="card">
  <div class="card-body card-padding">

    <strong>Agregar valoración:</strong><br>
    <select class="selectpicker form-control" id="valoration_type_select">
      <% ValorationType.all.each do |vt| %>
      <option value="<%= vt.id %>"><%= vt.name %></option>
      <% end %>
    </select>
    <a class="btn btn-primary btn-block waves-effect"
       id="new_valoration_btn" url="<%= new_valoration_doctor_expedients_path %>">
      Agregar
    </a>

    <hr>

    <strong>Agregar nota médica:</strong><br>
    <select class="selectpicker form-control" id="annotation_type_select">
      <% MedicalAnnotationType.all.each do |vt| %>
          <option value="<%= vt.id %>"><%= vt.name %></option>
      <% end %>
    </select>
    <a class="btn btn-primary btn-block waves-effect"
       id="new_annotation_btn"
       url="<%= load_annotation_fields_cli_hospitalizations_path %>">
      Agregar</a>


  </div>
</div>

app/views/cli/hospitalizations/_notes.html.erb
<div class="card">
  <div class="card-body card-padding">
    <h3>Notas médicas</h3>
    <table class="table">
      <thead>
      <tr>
        <th></th>
        <th style="width: 25%">Fecha</th>
        <th>Anotación</th>
        <th>Responsable</th>
        <th style="width: 130px;"></th>
      </tr>
      </thead>
      <tbody>
      <% @hospitalization.medical_annotations.order('created_at DESC').each do |ma| %>
          <tr>
            <td>
              <label annotation="<%= ma.id %>" class="show_annotation_btn">
                <i class="zmdi zmdi-caret-right-circle zmdi-hc-fw"></i>
              </label>
            </td>
            <td><%= ma.created_at.strftime('%d/%m/%Y %l:%M %p') %></td>
            <td><%= ma.medical_annotation_type.name %></td>
            <td><%= ma.user.person.full_name %></td>
            <td>
              <a target="_blank" class="btn btn-primary btn-icon waves-effect waves-circle waves-float" href="<%= medical_annotation_pdfs_path(ma) %>">
                <i class="zmdi zmdi-print"></i>
              </a>

              <% if ma.medical_annotation_type.require_upload %>
                  <a class="btn bgm-deeporange btn-icon waves-effect waves-circle waves-float upload_annotation_file" annotation_id="<%= ma.id %>">
                    <i class="zmdi zmdi-upload"></i>
                  </a>
              <% end %>

            </td>
          </tr>
          <tr id="full_annotation_<%= ma.id %>" style="display: none;">
            <td colspan="6">
              <% ma.annotation_fields.each do |field|
                data = JSON.parse(field.medical_annotation_field.config)
              %>
                  <div class="col-md-4">

                    <% case data['html_type']
                         when "checkbox" %>

                        <%= data['label'] %><br>
                        <%
                          options = data['options'].split("|")
                          values = field.data.split("|")
                        %>

                        <% options.each do |o|
                          checked = ""
                          checked = "checked" if values.include? o
                        %>
                            <label class="checkbox checkbox-inline m-r-20">
                              <input type="checkbox" <%= checked %>>
                              <i class="input-helper"></i>
                              <%= o %>
                            </label><br>
                        <% end %>

                    <% else %>
                        <strong><%= data['label'] %></strong><br>
                        <label class="annotation_data_label">
                          <%= field.data %>
                        </label>
                    <% end %>


                  </div>
              <% end %>


              <% if ma.medical_annotation_files.size > 0 %>
              <div class="col-md-12">
                <strong>Archivos subidos</strong>

                <table class="table">
                  <thead>
                  <tr>
                    <th>Fecha</th>
                    <th>Subido por</th>
                    <th>Notas</th>
                    <th>Descarga</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% ma.medical_annotation_files.each do |file| %>
                      <tr>
                        <td><%= file.created_at.strftime('%d/%m/%Y') %></td>
                        <td><%= file.user.person.full_name %></td>
                        <td><%= file.notes %></td>
                        <td>
                          <% basename = File.basename file.document.url %>
                          <%= basename %>
                          <a target="_blank" class="btn bgm-lightgreen btn-icon waves-effect waves-circle waves-float"
                             href="<%= download_cli_medical_annotation_files_path(file) %>">
                            <i class="zmdi zmdi-download"></i>
                          </a>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>



              </div>
              <% end %>


            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/cli/hospitalizations/_show_modals.html.erb
<div class="modal fade" id="add_valoration_modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="">Agregar valoración</h4>
      </div>
      <div class="modal-body">
        <%= hidden_field_tag 'new_valoration_valoration_type_id','' %>
        <div id="valoration_fields"></div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-link" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="save_valoration_btn" url="<%= save_medical_valoration_cli_hospitalizations_path %>">Aceptar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="add_annotation_modal" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="">Agregar anotación</h4>
      </div>
      <div class="modal-body">
        <%= hidden_field_tag 'new_annotation_annotation_type_id','' %>
        <div id="annotation_fields"></div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-link" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="save_annotation_btn" url="<%= save_medical_annotation_cli_hospitalizations_path %>">Aceptar</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="add_annotation_file_modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="">Agregar archivo</h4>
      </div>
      <div class="modal-body">
        <%= form_for [:cli, @annotation_file] do |f| %>
            <%= f.hidden_field :medical_annotation_id %>
            <%= hidden_field_tag 'source', 'hospitalization' %>
            <%= hidden_field_tag 'hospitalization_id', @hospitalization.id %>
            <div class="row">
              <div class="col-md-12">
                <div class="fileinput fileinput-new" data-provides="fileinput">
                                        <span class="btn btn-primary btn-file m-r-10">
                                            <span class="fileinput-new">Seleccionar archivo</span>
                                            <span class="fileinput-exists">Cambiar</span>
                                          <%= f.file_field :document %>
                                        </span>
                  <span class="fileinput-filename"></span>
                  <a href="#" class="close fileinput-exists" data-dismiss="fileinput">&times;</a>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group fg-line">
                  <strong>Notas</strong>
                  <%= f.text_area :notes, :class=>"form-control input-lg", :placeholder => "Notas" %>

                </div>
              </div>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-link" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="save_annotation_file_btn">Aceptar</button>
      </div>
    </div>
  </div>
</div>

app/views/cli/hospitalizations/_valorations.html.erb
<div class="card">
  <div class="card-body card-padding">
    <h3>Valoraciones</h3>
    <table class="table table-striped">
      <thead>
      <tr>
        <th></th>
        <th style="width: 25%">Fecha</th>
        <th>Valoración</th>
        <th>Responsable</th>
        <th>Resumen de valoración</th>
      </tr>
      </thead>
      <tbody>
      <% @hospitalization.patient_valorations.order('created_at DESC').each do |pv| %>
      <tr>
        <td>
          <label patient_valoration="<%= pv.id %>" class="show_valoration_btn">
            <i class="zmdi zmdi-caret-right-circle zmdi-hc-fw"></i>
          </label>

        </td>
        <td><%= pv.created_at.strftime('%d/%m/%Y %l:%M %p') %></td>
        <td><%= pv.valoration_type.name %></td>
        <td><%= pv.user.person.full_name %></td>
        <td>
          <% idx = 0
            max = (pv.patient_valoration_fields.size > 4 ) ? 4 :  pv.patient_valoration_fields.size
          %>
          <% pv.patient_valoration_fields.each do |field|
            if idx < max
          %>
                <strong><%= field.valoration_field.name %>: </strong>
                  <label class="valoration_data_label"><%= field.data %></label><%= idx < (max - 1) ? ',':'' %>
                  &nbsp;
          <%
            end
            idx += 1
            end %>
        </td>
      </tr>
      <tr id="full_valoration_<%= pv.id %>" style="display: none;">
        <td colspan="5">
          <% pv.patient_valoration_fields.each do |field| %>
              <div class="col-md-4">
                <strong><%= field.valoration_field.name %></strong><br>
                <% if !field.valoration_field.collection_type.present? %>
                    <label class="valoration_data_label"><%= field.data %></label>
                <% else
                  str = ""
                %>

                <% case field.valoration_field.collection_type %>
                <% when Const::VALORATION_COLLECTION_TYPE_TRIAGE
                  rec = Triage.find(field.data)
                  if rec.present?
                    str = rec.level
                  end
                %>

                <% end %>

                    <label class="valoration_data_label"><%= str %></label>

                <% end %>
              </div>
          <% end %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/cli/hospitalizations/pdf_header.html.erb
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
</head>
<body>
<header>

</header>
</body>
</html>